
SRCS = BGM.cpp DPCM.cpp DPCMinfo.cpp Envelop.cpp FileInput.cpp FileOutput.cpp \
 MMLfile.cpp mml_Address.cpp mml_general.cpp mml_repeat.cpp mml_note.cpp mml_poke.cpp \
 MusicEvent.cpp MusicFile.cpp MusicHeader.cpp MusicItem.cpp MusicTrack.cpp N163.cpp \
 nsc.cpp Option.cpp SE.cpp StdAfx.cpp Sub.cpp TrackSet.cpp VRC7.cpp FDSC.cpp FDSM.cpp \
 SearchPass.cpp Patch.cpp
